[package]
name = "frametool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
framework_lib = { git = "https://github.com/FrameworkComputer/framework-system.git", version = "0.4.5" }
